server:
  port: 8081

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: banking-monolith
  datasource:
    url: jdbc:postgresql://localhost:5433/banking_monolith_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

app:
  jwt:
    secret: thisIsAVeryLongSecretKeyForJWTTokenGenerationThatMustBeAtLeast512BitsLongForHS512Algorithm1234567890
    expiration: 3600000
    refresh-expiration: 86400000

logging:
  level:
    com.springbank: DEBUG