server:
  port: 8091

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: fraud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/banking_fraud_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
